version: 2
updates:
  - package-ecosystem: "maven"
    directory: "/"        # pom.xml tổng ở root
    schedule:
      interval: "daily"
      time: "00:00"
      timezone: "Asia/Bangkok"
    target-branch: "main"
    open-pull-requests-limit: 10
    labels:
      - "dependencies"
      - "maven"
    commit-message:
      prefix: "deps"
      include: "scope"

  # Dependabot update Actions trong .github/workflows
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "00:00"
      timezone: "Asia/Bangkok"
    labels:
      - "dependencies"
      - "github-actions"
