name: Maven CI
on:
  push:
    branches:
      - "main"
    pull_request:
      - "main"

jobs:
  build-test:
    name: Build & Test (${{ matrix.module }})
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        module:
          - "common"
          - "core-service"
          - "gateway-server"
          - "business-service"
          - "eureka-server"
          - "config-server"

    defaults:
      run:
        working-directory:

    steps:
      - name: Checkout source
        uses: actions/checkout@v5

      - name: Set up JDK 21
        uses: actions/setup-java@v5
        with:
          distribution: "temurin"
          java-version: '21'
          cache: 'maven'

      - name: Build & run tests ${{ matrix.module }}
        run: mvn -B -ntp -pl ${{ matrix.module }} -am clean verify

      - name: Generate JaCoCo aggregate report
        run: mvn -B -ntp jacoco:report-aggregate

